sudo: required
language: r
warnings_are_errors: false
dist: trusty

# enable this to run (slow & fragile) tests of sampler validity before releases
env:
  - RELEASE_CANDIDATE=false

# these are dependencies of suggested packagesi for which there are binaries,
# add them here to try to reduce installation time
r_binary_packages:
  - abind
  - coda
  - codetools
  - colorspace
  - DBI
  - digest
  - foreign
  - ggplot2
  - inline
  - lattice
  - MASS
  - MCMCpack
  - mgcv
  - mvtnorm
  - nlme
  - plyr
  - Rcpp
  - rpart
  - rstan
  - stringr
  - survival
  - XML

r_packages:
  - reticulate
  - tensorflow
  - R6
  - testthat
  - covr
  - DiagrammeR
  - knitr
  - rmarkdown
  - rsvg
  - bayesplot
  - extraDistr
  - devtools
  - tidyverse

r_github_packages:
  - rich-iannone/DiagrammeRsvg
  - rmcelreath/rethinking

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - libmagick++-dev
      - wget
      - libatlas3gf-base
      - libatlas-dev
      - python-joblib
      - python-dev
      - libv8-dev

before_install:
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user 'tensorflow==1.10'
  - pip install --user 'tensorflow-probability'

after_success:
  - Rscript -e "covr::codecov()"

email:
  on_success: change
  on_failure: change
